import {test} from 'node:test';import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {migrate,status} from '../db.js';import {initializeFresh,enableValidation} from '../fresh.js';import {workOne} from '../worker.js';import {createMetadataTransport} from '../transport.js';import {folderMetadata} from '../checkpoint.js';
test('synthetic fresh scan starts empty and paused then commits one validation page',async()=>{const db=new PGlite();try{await migrate(db);await initializeFresh(db,{scanId:'s',root:{id:'root',accountId:'a'}});let calls=0;const source=async()=>{calls++;return {files:[{id:'pdf',name:'p.pdf'}],nextPage:2};};await workOne(db,'s','w',source);assert.equal(calls,0);await enableValidation(db,'s');await workOne(db,'s','w',source);const s=await status(db,'s');assert.equal(Number(s.unique_pdfs),1);assert.equal(Number(s.missing_size_pdfs),1);assert.equal(s.crawling_enabled,false);}finally{await db.close();}});
test('synthetic full nested folder structure retains request data and strips credentials recursively',()=>{assert.deepEqual(folderMetadata({id:'x',account:{id:'a',nonce:'secret',nested:{shared:true,authorization:'secret'}},custom:[1,{x:'y',url:'https://content.invalid'}],cookie:'secret'}),{id:'x',account:{id:'a',nested:{shared:true}},custom:[1,{x:'y'}]});});
test('synthetic authenticated IGD transcript preserves shortcode 7 nested folder request and Bosch-shaped 379-item response',async()=>{
 const originalFetch=globalThis.fetch,oldUser=process.env.SAG_USERNAME,oldPassword=process.env.SAG_PASSWORD;
 const folder={id:'bosch-fixture',accountId:'a',name:'Bosch',account:{id:'a',shared:true},customField:'keep',pageNumber:1};
 const files=Array.from({length:379},(_,i)=>({id:String(i),name:i<373?i+'.pdf':'folder'+i,type:i<373?'application/pdf':'application/vnd.google-apps.folder'}));
 const html='<script>var igd = {"nonce":"synthetic-nonce","ajaxUrl":"https://servicealliancegroup.com/legacy/wp-admin/admin-ajax.php"};</script>';
 let calls=0;process.env.SAG_USERNAME='synthetic-user';process.env.SAG_PASSWORD='synthetic-password';
 globalThis.fetch=async(url,options)=>{calls++;const uri=String(url);if(uri.endsWith('admin-ajax.php')){const body=options.body;assert.equal(body.get('action'),'igd_get_files');assert.equal(body.get('shortcodeId'),'7');assert.equal(body.get('data[folder][account][shared]'),'true');assert.equal(body.get('data[folder][customField]'),'keep');assert.equal(body.get('data[folder][pageNumber]'),'1');return new Response(JSON.stringify({success:true,data:{files,count:379,nextPageNumber:0}}),{headers:{'content-type':'application/json'}});}if(uri.endsWith('/legacy/')&&options.method==='POST'){const response=new Response('',{status:302,headers:{location:'https://servicealliancegroup.com/legacy/member-dashboard/'}});Object.defineProperty(response,'url',{value:uri});return response;}const response=new Response(html);Object.defineProperty(response,'url',{value:uri});return response;};
 try{const result=await createMetadataTransport()(folder);assert.equal(result.files.length,379);assert.equal(result.files.filter(f=>f.type==='application/pdf').length,373);assert.equal(result.nextPage,null);assert.equal(calls,6);}
 finally{globalThis.fetch=originalFetch;if(oldUser===undefined)delete process.env.SAG_USERNAME;else process.env.SAG_USERNAME=oldUser;if(oldPassword===undefined)delete process.env.SAG_PASSWORD;else process.env.SAG_PASSWORD=oldPassword;}
});
