import {test} from 'node:test';import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {migrate,status} from '../db.js';import {parseCheckpoint} from '../checkpoint.js';import {importCheckpoint} from '../importer.js';
export function fixture(){return {version:1,root:'root',account:'a',state:{},seen:['a:root','a:bad'],done:['a:root'],queue:[],failed:[{key:'a:bad',folder:{id:'bad',accountId:'a',name:'UNSORTED MISC PDF FILES',pageNumber:3},round:2}],pdfs:[['a:f1',{id:'f1',accountId:'a',name:'one.pdf',size:'10',parentId:'root',token:'secret'}],['a:f2',{id:'f2',accountId:'a',name:'two.pdf',size:'20',parentId:'root'}]]};}
export const expected={completedFolders:1,uniquePdfs:2,totalBytes:'30',unresolvedFolders:1};
export async function setup(){const db=new PGlite();await migrate(db);return db;}
test('dry run preserves keys, strips secrets, and leaves legacy parent completeness unknown',()=>{const s=fixture();s.pdfs[0][1].accountId='different';const p=parseCheckpoint(s,{expected});assert.equal(p.files[0].account,'a');assert.equal(p.report.accountDifferences,1);assert.equal(p.files[0].metadata.token,undefined);assert.equal(p.folders[0].metadata,null);assert.equal(p.report.databaseChanges,false);assert.equal(p.relationships.length,2);});
test('malformed identities, duplicates, invalid sizes and mismatches fail',()=>{for(const mutate of [s=>s.pdfs.push(s.pdfs[0]),s=>s.pdfs[0][1].size='11',s=>s.pdfs[0][1].size='-1',s=>s.done.push('a:bad'),s=>s.pdfs[0][1].id='other']){const s=fixture();mutate(s);assert.throws(()=>parseCheckpoint(s,{expected}));}});
test('atomic import, repeat import, incomplete relationships, blocked jobs and restart status',async()=>{const db=await setup();try{await importCheckpoint(db,fixture(),{scanId:'s',expected});await importCheckpoint(db,fixture(),{scanId:'s',expected});const s=await status(db,'s');assert.equal(Number(s.unique_pdfs),2);assert.equal(s.total_unique_bytes,'30');assert.equal(Number(s.blocked_jobs),1);assert.equal(s.crawling_enabled,false);assert.equal((await db.query('SELECT source_metadata FROM folders WHERE crawl_status=\'completed\'')).rows[0].source_metadata,null);assert.equal((await db.query('SELECT DISTINCT relationship_completeness FROM folder_files')).rows[0].relationship_completeness,'unknown');}finally{await db.close();}});
test('database size conflict rolls back all inserted scan state',async()=>{const db=await setup();try{await db.query("INSERT INTO files(account_id,drive_file_id,size_bytes,provenance,metadata_completeness) VALUES('a','f2',21,'test','partial')");await assert.rejects(importCheckpoint(db,fixture(),{scanId:'s',expected}),/Conflicting file size/);assert.equal((await db.query('SELECT count(*) FROM scan_runs')).rows[0].count,0);assert.equal((await db.query('SELECT count(*) FROM folders')).rows[0].count,0);assert.equal((await db.query('SELECT count(*) FROM files')).rows[0].count,1);}finally{await db.close();}});
test('post-write reconciliation mismatch rolls back the complete import',async()=>{const db=await setup();try{await db.exec(`CREATE FUNCTION corrupt_import_size() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.size_bytes=NEW.size_bytes+1; RETURN NEW; END $$; CREATE TRIGGER inject_bad_total BEFORE INSERT ON files FOR EACH ROW EXECUTE FUNCTION corrupt_import_size();`);await assert.rejects(importCheckpoint(db,fixture(),{scanId:'s',expected}));assert.equal((await db.query('SELECT count(*) FROM scan_runs')).rows[0].count,0);assert.equal((await db.query('SELECT count(*) FROM files')).rows[0].count,0);}finally{await db.close();}});
test('production acceptance totals dry-run on synthetic catalog',()=>{const saved={version:1,root:'root',account:'a',state:{},seen:Array.from({length:218},(_,i)=>`a:folder${i}`),done:Array.from({length:217},(_,i)=>`a:folder${i}`),queue:[],failed:[{key:'a:folder217',folder:{id:'folder217',name:'UNSORTED MISC PDF FILES'},error:'HTTP 500'}],pdfs:Array.from({length:92266},(_,i)=>[`a:file${i}`,{id:`file${i}`,accountId:'a',name:`${i}.pdf`,size:i===0?'146394300662':'1',parentId:'folder0'}])};saved.failed[0].folder.accountId='a';saved.root='1-0mICiR1DYKpV73iISmEV8DcuyTe-Pc-';saved.account='11257309238295447992';const p=parseCheckpoint(saved);assert.equal(p.report.uniquePdfs,92266);assert.equal(p.report.totalBytes,'146394392927');assert.equal(p.report.completedFolders,217);assert.equal(p.report.blockedJobs,1);});

test('final count reconciliation failure rolls back relationships and files',async()=>{const db=await setup();try{await db.exec(`CREATE FUNCTION omit_scan_file() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$; CREATE TRIGGER inject_missing_file BEFORE INSERT ON scan_files FOR EACH ROW EXECUTE FUNCTION omit_scan_file();`);await assert.rejects(importCheckpoint(db,fixture(),{scanId:'s',expected}),/Reconciliation mismatch: uniquePdfs/);assert.equal((await db.query('SELECT count(*) FROM files')).rows[0].count,0);assert.equal((await db.query('SELECT count(*) FROM folders')).rows[0].count,0);}finally{await db.close();}});
