import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Client} from 'pg';
import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {migrate,status} from '../db.js';
import {initializeFresh,setPaused,enableValidation} from '../fresh.js';
import {claimJob,processPage,failJob,heartbeat} from '../jobs.js';
import {workOne} from '../worker.js';
import {comparisonReport} from '../reconciliation.js';
import {appendParams} from '../transport.js';
const url=process.env.TITAN_TEST_DATABASE_URL;
if(url&&!['127.0.0.1','localhost','[::1]'].includes(new URL(url).hostname))throw new Error('Real tests require loopback isolated PostgreSQL');
const pdf={id:'f',name:'f.pdf',size:'10',type:'application/pdf'};
const root={id:'root',accountId:'a',name:'ROOT',type:'application/vnd.google-apps.folder',account:{id:'a',nested:{shared:true}},customField:['x',{y:2}]};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(fn){
 const schema='titan_test_'+randomUUID().replaceAll('-','');const admin=new Client({connectionString:url});await admin.connect();await admin.query('CREATE SCHEMA '+schema);
 const connections=[];const connect=async()=>{const db=new Client({connectionString:url});await db.connect();await db.query('SET search_path TO '+schema);connections.push(db);return db;};
 try{const db=await connect();await migrate(db);await fn({db,connect,schema});}
 finally{for(const db of connections)await db.end();await admin.query('DROP SCHEMA '+schema+' CASCADE');await admin.end();}
}
const real=(name,fn)=>test('real PostgreSQL: '+name,{skip:!url},()=>fixture(fn));
const init=async db=>{await initializeFresh(db,{scanId:'s',root});await setPaused(db,'s',false);};
const ready=async db=>db.query("UPDATE scan_runs SET next_request_at=now()-interval '1 second'");
function child(mode,arg,schema){const proc=spawn(process.execPath,[new URL('./real-child.js',import.meta.url).pathname,mode,...(arg?[JSON.stringify(arg)]:[])],{env:{...process.env,TITAN_TEST_SCHEMA:schema},stdio:['ignore','pipe','pipe']});let output='',error='';proc.stdout.on('data',s=>output+=s);proc.stderr.on('data',s=>error+=s);const done=new Promise((resolve,reject)=>proc.on('exit',(code,signal)=>code===0||signal==='SIGKILL'?resolve({output,signal}):reject(new Error(error))));return {proc,done};}
real('empty migrations, repeat migrations, paused initialization and duplicate root guard',async({db,connect})=>{await migrate(db);await initializeFresh(db,{scanId:'s',root});assert.equal(await claimJob(db,'s','no'),null);assert.equal((await status(db,'s')).crawling_enabled,false);assert.equal(Number((await status(db,'s')).unique_pdfs),0);await assert.rejects(initializeFresh(db,{scanId:'duplicate',root}),/active scan/);const other=await connect();assert.equal((await status(other,'s')).status,'paused');});
real('dedup, shortcuts, folder relationships, replay, nested folder retention and completed protection',async({db})=>{await init(db);const lease=await claimJob(db,'s','w');const page={files:[pdf,pdf,{...pdf,id:'shortcut',shortcutDetails:{targetId:'f',targetMimeType:'application/pdf'}},{...root,id:'child'}],nextPage:2};await processPage(db,lease,page);assert.deepEqual(await processPage(db,lease,page),{alreadyCommitted:true});await assert.rejects(processPage(db,lease,{files:[]}),/replay differs/);assert.deepEqual((await db.query("SELECT source_metadata FROM folders WHERE drive_folder_id='child'")).rows[0].source_metadata.account,root.account);await ready(db);let next=await claimJob(db,'s','w2');await processPage(db,next,{files:[pdf]});await ready(db);next=await claimJob(db,'s','w3');await processPage(db,next,{files:[pdf,{...root,id:'child'}]});assert.equal(Number((await status(db,'s')).unique_pdfs),1);assert.equal(Number((await db.query('SELECT count(*) FROM folder_files')).rows[0].count),2);await ready(db);assert.equal(await claimJob(db,'s','done'),null);});
real('rollback after mid-page failure leaves all rows and pagination retryable',async({db})=>{await init(db);const lease=await claimJob(db,'s','w');await assert.rejects(processPage(db,lease,{files:[pdf,{...pdf,size:'11'}],nextPage:2}),/Conflicting/);assert.equal(Number((await status(db,'s')).unique_pdfs),0);assert.equal(Number((await db.query('SELECT count(*) FROM processed_pages')).rows[0].count),0);await processPage(db,lease,{files:[pdf],nextPage:2});});
real('two simultaneous connections cannot claim the same job',async({db,connect})=>{await init(db);const other=await connect();const claims=await Promise.all([claimJob(db,'s','one'),claimJob(other,'s','two')]);assert.equal(claims.filter(Boolean).length,1);});
real('multiple real connections claim distinct jobs within bounded concurrency',async({db,connect})=>{await init(db);const lease=await claimJob(db,'s','seed');await processPage(db,lease,{files:[{...root,id:'child1'},{...root,id:'child2'}]});await db.query('UPDATE scan_runs SET max_concurrency=2');await ready(db);const other=await connect();const a=await claimJob(db,'s','one');await ready(db);const b=await claimJob(other,'s','two');assert.notEqual(a.id,b.id);await ready(db);assert.equal(await claimJob(db,'s','three'),null);});
real('expiry, heartbeat, fencing token and stale worker rejection',async({db,connect})=>{await init(db);const a=await claimJob(db,'s','old');await heartbeat(db,a);await db.query("UPDATE crawl_jobs SET lease_expires_at=now()-interval '1 second'");await ready(db);const other=await connect(),b=await claimJob(other,'s','new');assert.equal(Number(b.lease_token),Number(a.lease_token)+1);await assert.rejects(processPage(db,a,{files:[pdf]}),/Stale/);await assert.rejects(failJob(db,a),/Stale/);await processPage(other,b,{files:[pdf]});});
real('pause persists across new process and drains an in-flight page',async({db,schema})=>{await init(db);const lease=await claimJob(db,'s','w');await setPaused(db,'s',true);const before=JSON.parse((await child('status',null,schema).done).output);assert.equal(before.crawling_enabled,false);await processPage(db,lease,{files:[pdf],nextPage:2});assert.equal((await status(db,'s')).status,'paused');await ready(db);assert.equal(await claimJob(db,'s','no'),null);});
real('retry timing, sanitized errors, retry cap and expired crash cap',async({db})=>{await init(db);await db.query('UPDATE scan_runs SET max_attempts=2');const a=await claimJob(db,'s','w');await failJob(db,a,{retryAfterSeconds:300});await ready(db);assert.equal(await claimJob(db,'s','wait'),null);await db.query("UPDATE crawl_jobs SET available_after=now()-interval '1 second'");const b=await claimJob(db,'s','retry');await failJob(db,b);assert.equal(Number((await status(db,'s')).blocked_jobs),1);assert.equal(Number((await status(db,'s')).failed_folders),1);assert.deepEqual((await db.query('SELECT last_error FROM crawl_jobs')).rows[0].last_error,{code:'metadata_page_blocked'});});
real('rate gate and worker invocation only after explicit enable',async({db})=>{await initializeFresh(db,{scanId:'s',root});let calls=0;const fetch=async f=>{calls++;assert.deepEqual(f.account,root.account);return {files:[pdf],nextPage:2};};await workOne(db,'s','w',fetch);assert.equal(calls,0);await setPaused(db,'s',false);assert.equal((await workOne(db,'s','w',fetch)).committed,true);await workOne(db,'s','w',fetch);assert.equal(calls,1);});
real('SIGKILL before page commit rolls back then a new process resumes',async({db,schema})=>{await init(db);const lease=await claimJob(db,'s','killed');await db.query(`CREATE FUNCTION hold_test_page() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN PERFORM pg_sleep(30); RETURN NEW; END $$`);await db.query('CREATE TRIGGER hold_page BEFORE INSERT ON processed_pages FOR EACH ROW EXECUTE FUNCTION hold_test_page()');const c=child('page',lease,schema);let held=false;for(let i=0;i<100;i++){const rows=(await db.query("SELECT wait_event FROM pg_stat_activity WHERE application_name='titan-test-child' AND wait_event='PgSleep'")).rows;if(rows.length){held=true;break;}await delay(50);}assert.equal(held,true);c.proc.kill('SIGKILL');await c.done;await db.query('DROP TRIGGER hold_page ON processed_pages');assert.equal(Number((await status(db,'s')).unique_pdfs),0);await db.query("UPDATE crawl_jobs SET lease_expires_at=now()-interval '1 second'");await ready(db);const reopened=JSON.parse((await child('resume',null,schema).done).output);assert.equal(Number(reopened.unique_pdfs),1);});
real('commit survives process exit and a completely new process resumes persisted pagination',async({db,schema})=>{await init(db);const lease=await claimJob(db,'s','first');await child('page',lease,schema).done;await ready(db);const reopened=JSON.parse((await child('resume',null,schema).done).output);assert.equal(Number(reopened.unique_pdfs),2);assert.equal(reopened.total_unique_bytes,'30');assert.equal(reopened.status,'completed');assert.ok(reopened.last_committed_page_time);});
test('synthetic browser-compatible nested POST encoding',()=>{const body=new URLSearchParams();appendParams(body,'data',{folder:root});assert.equal(body.get('data[folder][account][nested][shared]'),'true');assert.equal(body.get('data[folder][customField][1][y]'),'2');});

real('historical deltas and retained baseline differences accept legitimate filename and size changes',async({db})=>{
 await init(db);await processPage(db,await claimJob(db,'s','old'),{files:[pdf,{id:'removed',name:'removed.pdf',size:'4'}]});
 await initializeFresh(db,{scanId:'fresh',root});await setPaused(db,'fresh',false);await processPage(db,await claimJob(db,'fresh','new'),{files:[{...pdf,name:'renamed.pdf',size:'12'},{id:'new',name:'new.pdf'}]});
 const report=await comparisonReport(db,'fresh',{baselineScanId:'s'});assert.equal(report.details.newPdfs.length,1);assert.equal(report.details.noLongerObserved.length,1);assert.equal(report.details.changedSizes.length,1);assert.equal(report.details.changedFilenames.length,1);assert.equal(report.current.total_unique_bytes,'12');assert.equal(Number(report.current.missing_size_pdfs),1);assert.equal((await status(db,'s')).total_unique_bytes,'14');assert.equal((await comparisonReport(db,'fresh')).details,null);
});
real('repeated expired worker leases terminate at the retry ceiling',async({db})=>{
 await init(db);await db.query('UPDATE scan_runs SET max_attempts=1');await claimJob(db,'s','dead');await db.query("UPDATE crawl_jobs SET lease_expires_at=now()-interval '1 second'");await ready(db);assert.equal(await claimJob(db,'s','no-loop'),null);assert.equal(Number((await status(db,'s')).blocked_jobs),1);
});

real('one-page validation budget pauses automatically after commit',async({db})=>{await initializeFresh(db,{scanId:'s',root});await enableValidation(db,'s');assert.equal((await workOne(db,'s','w',async()=>({files:[pdf],nextPage:2}))).committed,true);assert.equal((await status(db,'s')).crawling_enabled,false);await ready(db);assert.equal(await claimJob(db,'s','no'),null);});
real('isolated HTTP startup, persistent status and restart while paused never contact source',async({db,schema})=>{
 await initializeFresh(db,{scanId:'s',root});
 const run=async()=>{
  const proc=spawn(process.execPath,[new URL('../app.js',import.meta.url).pathname],{env:{...process.env,TITAN_CATALOG_DATABASE_URL:url,TITAN_SCAN_ID:'s',PGOPTIONS:'-c search_path='+schema,PORT:'55440'},stdio:['ignore','pipe','pipe']});let errors='';proc.stderr.on('data',s=>errors+=s);
  try{let response;for(let i=0;i<100;i++){try{response=await fetch('http://127.0.0.1:55440/status');break;}catch{await delay(30);}}assert.ok(response,errors);const result=await response.json();assert.equal(result.crawling_enabled,false);assert.equal(result.authority,'postgresql');assert.equal(Number(result.unique_pdfs),0);assert.ok('queued_jobs' in result);assert.equal((await fetch('http://127.0.0.1:55440/health')).status,200);}
  finally{const exited=new Promise(resolve=>proc.once('exit',resolve));proc.kill('SIGTERM');await exited;}
 };
 await run();await run();assert.equal(Number((await status(db,'s')).leased_jobs),0);
});

real('one failed folder preserves other folders and missing sizes fill from later metadata',async({db})=>{
 await init(db);await processPage(db,await claimJob(db,'s','root'),{files:[{...root,id:'bad'},{...root,id:'good'}]});await ready(db);const bad=await claimJob(db,'s','bad');await failJob(db,bad,{retryable:false});await ready(db);const good=await claimJob(db,'s','good');await processPage(db,good,{files:[{id:'unknown',name:'unknown.pdf'},{id:'unknown',name:'unknown.pdf',size:'25'}]});const s=await status(db,'s');assert.equal(Number(s.failed_folders),1);assert.equal(Number(s.completed_folders),2);assert.equal(s.total_unique_bytes,'25');assert.equal(Number(s.missing_size_pdfs),0);assert.equal(Number(s.unique_pdfs),1);
});
